/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplevotingsystem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author UMAGA GEE
 */
public class changePassword extends java.awt.Frame {
        Connection con=null;
    Statement stm=null;
    ResultSet rs=null;
    PreparedStatement ps=null;
    String username;

    /**
     * Creates new form changePassword
     */
    public changePassword() {
        initComponents();
          setLocationRelativeTo(null);
        // con=ConnectionToDatabase.conn();
         con=creatConnection.conn();
         lblMatch1.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */



    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblMatch1 = new javax.swing.JLabel();
        oldPass = new javax.swing.JPasswordField();
        Cpass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        newPass = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("PROCEED");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 340, 50));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("CHANGE PASSWORD");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 30));

        lblMatch1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMatch1.setForeground(java.awt.Color.red);
        lblMatch1.setText("* Password do not match");
        jPanel1.add(lblMatch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 260, -1));

        oldPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(oldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 320, 40));

        Cpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpassActionPerformed(evt);
            }
        });
        Cpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CpassKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CpassKeyTyped(evt);
            }
        });
        jPanel1.add(Cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 320, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Confirm Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("New Password");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Old Password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        newPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 320, 40));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
         JOptionPane.showMessageDialog(null, "You have to Logout First");
    }//GEN-LAST:event_exitForm

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Opass=oldPass.getText();
        String  Npass=newPass.getText().trim();
        String   cPass=Cpass.getText();
        
         //Hashing Password
//PasswordHashing hp=new PasswordHashing();
//String hashedPassword=hp.hashPassword(Npass, Npass);
//String hashedPassword1=hp.hashPassword(Opass, Opass);
//      

        if( Opass.equals("") || Npass.equals("") || cPass.equals("")){
            JOptionPane.showMessageDialog(null, "One or More field is empty");

        }

        else{

            try{

                    if(!Npass.equals(cPass)){
                        lblMatch1.show();
                    }else{
                        ps=con.prepareStatement("Select * from Admin WHERE  Password=?  ");
                        ps.setString(1, Opass);
                        rs=ps.executeQuery();
                        if(rs.next()){
                            String pass=rs.getString("Password");

                            if( (pass.equals(Opass)) ){
                                String sql="update ADMIN set Password=?";
                                ps=con.prepareStatement(sql);
                                ps.setString(1, Npass);
                                ps.executeUpdate();
                                JOptionPane.showMessageDialog(null, "Your password has Successfully been Change");
                                LogIn l=new LogIn();
                                l.show();
                                this.dispose();
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Wrong Details ");
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Wrong Credentials 2 ");
                        }

                    }

                

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void CpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpassActionPerformed

    }//GEN-LAST:event_CpassActionPerformed

    private void CpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CpassKeyReleased

    }//GEN-LAST:event_CpassKeyReleased

    private void CpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CpassKeyTyped

    }//GEN-LAST:event_CpassKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
            homePage hp=new homePage();
           hp.show();
          this.dispose();
       }catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
       }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changePassword().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Cpass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMatch1;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JPasswordField oldPass;
    // End of variables declaration//GEN-END:variables
}
