/*
  * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplevotingsystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author UMAGAGEE
 */
public class LogIn extends javax.swing.JFrame {
Connection con=null;
    Statement stm=null;
    ResultSet rs=null;
    PreparedStatement ps=null;
    String username;
    
    /**
     * Creates new form LogIn
     */
    public LogIn() {
       
        initComponents();
        setLocationRelativeTo(null);
         //con=ConnectionToDatabase.conn();
          con=creatConnection.conn();
          
         currentDate ();
        // login_Hold();
    }
//    
//    private static String hashPassword(String plainTextPassword){
//    return Bcrypt.hashpw(plainTextPassword,Bcrypt.gensalt());
//    }

  
    
     public int currentDate (){
        
        Calendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        txt_date.setText((month+1)+"/"+day+"/"+year);
        return year;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        UserName = new javax.swing.JTextField();
        Passwrd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblForget = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 190, 30));

        Passwrd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(Passwrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 190, 30));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("LOGIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        txt_date.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_date.setOpaque(true);
        jPanel1.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 70, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblForget.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblForget.setText("Forget Password?");
        lblForget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgetMouseClicked(evt);
            }
        });
        jPanel1.add(lblForget, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 180, 20));

        jButton2.setBackground(new java.awt.Color(102, 255, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 80, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("UserName");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1 (5).jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String username=UserName.getText().toUpperCase().trim();
String storePassword=Passwrd.getText();
//Hashing Password
//PasswordHashing hp=new PasswordHashing();
//String hashedPassword=hp.hashPassword(storePassword, storePassword);
        try{

ps=con.prepareStatement("Select * from Admin WHERE UserName=? AND Password=?");
ps.setString(1, username);
ps.setString(2, storePassword);
rs=ps.executeQuery();
   if(rs.next()){
       String user=rs.getString("UserName");
       String pass=rs.getString("Password");
       
      
//       
//        Date currentDate = GregorianCalendar.getInstance().getTime();
//                DateFormat df = DateFormat.getDateInstance();
//                String dateString = df.format(currentDate);
//
//                 Date d = new Date();
//                 // SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
//               //   String timeString = sdf.format(d);
//                  
//                  SimpleDateFormat sd = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
//                //String dateString = sd.format(d);
                        
                 // String value0 = timeString;
                 // String value1 = dateString;
                  
                  ps=con.prepareStatement("INSERT INTO Audit (fk1_Username,LoginDate) values ('"+user+"',?)");
                  //Creating instance for Date and Time
                  java.sql.Timestamp date = new  java.sql.Timestamp(new java.util.Date().getTime());
                  ps.setTimestamp(1, date);
                  
                ps.executeUpdate();
                  
       
       if(user.equals(username) && (pass.equals(storePassword)) ){
       homePage ca = new homePage();
       ca.show();
       this.dispose();
       }else{
             JOptionPane.showMessageDialog(null, "Wrong Credentials "); 
       }
   } 
   else{
       JOptionPane.showMessageDialog(null, "Wrong Credentials ");
   }
   
   

}catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
    //
            UserName.setText(null);
            Passwrd.setText(null);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblForgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgetMouseClicked
try{
    ForgetPass fp = new ForgetPass();
    fp.show();
    this.dispose();

}catch(Exception e){
     JOptionPane.showMessageDialog(null, e.getMessage());
}
    }//GEN-LAST:event_lblForgetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
          UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Passwrd;
    public static javax.swing.JTextField UserName;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblForget;
    private javax.swing.JLabel txt_date;
    // End of variables declaration//GEN-END:variables

    private void login_Hold(){
     Passwrd.setEchoChar((char)0);
     Passwrd.setText("Enter Your Password : ");
     Passwrd.setForeground(Color.GRAY);
     UserName.setText("Enter Your ID : ");
     UserName.setForeground(Color.GRAY);
 }
}
