/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplevotingsystem;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author UMAGAGEE
 */
public class StudentInfo extends javax.swing.JFrame {
    Connection con=null;
    Statement stm=null;
    ResultSet rs=null;
    PreparedStatement ps=null;
    String imagePath=null;
   static String username;
    /**
     * Creates new form StudentInfo
     */
    public StudentInfo() {
        initComponents();
         setLocationRelativeTo(null);
       //  con=ConnectionToDatabase.conn();
       con=creatConnection.conn();
        showStudent();
        
         //showDept();
    }
  
       private void showStudent(){
        
        String sql1="Select  *  from student ";
    
         
     
  try{
      ps =con.prepareStatement(sql1);
      rs=ps.executeQuery();
    //pst.execute();
    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
     jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
    
            
    }catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e.getMessage());

    }finally {
try{
  rs.close();
      ps.close();
     
  }
  catch(Exception e) {
                 JOptionPane.showMessageDialog(null, e.getMessage());

                   }
      } 

}
    
  
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textStudentID = new javax.swing.JTextField();
        textFirstName = new javax.swing.JTextField();
        textLastName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonUpdate = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        comboGender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CmbLevel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STUDENT MANAGER", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bodoni MT Black", 1, 36))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 51, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("StudentID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        textStudentID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textStudentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textStudentIDKeyPressed(evt);
            }
        });
        jPanel1.add(textStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 60, 210, 30));

        textFirstName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(textFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 105, 210, 30));

        textLastName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(textLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 210, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Press Enter to Search ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonUpdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonUpdate.setForeground(new java.awt.Color(0, 0, 204));
        buttonUpdate.setText("UPDATE");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(buttonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 60));

        buttonDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(0, 0, 204));
        buttonDelete.setText("DELETE");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 110, 60));

        buttonClear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonClear.setForeground(new java.awt.Color(0, 0, 204));
        buttonClear.setText("CLEAR");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel2.add(buttonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 100, 60));

        buttonSave.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonSave.setForeground(new java.awt.Color(0, 0, 204));
        buttonSave.setText("SAVE");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 370, 200));

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("LastName");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        comboGender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female", "Other" }));
        comboGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGenderActionPerformed(evt);
            }
        });
        jPanel1.add(comboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 90, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("FirstName");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 106, -1, -1));

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 730, 480));

        CmbLevel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CmbLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level", "100", "200", "300", "400" }));
        CmbLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbLevelActionPerformed(evt);
            }
        });
        jPanel1.add(CmbLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed

        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
                
         if(textStudentID.getText()==null || textFirstName.getText()==null || textLastName.getText()==null||  comboGender.getSelectedItem()==null
              || CmbLevel.getSelectedItem()==null      ){
                JOptionPane.showMessageDialog(null, "One or More Fields is empty");
            
            }else{

                try{

                    String sql= "update STUDENT set FIRSTNAME=?,LEVEL=?, LASTNAME=?,GENDER=? where STUDENTID=?";

                    ps=con.prepareStatement(sql);

                    ps.setString(1, textFirstName.getText());
                    ps.setString(2, CmbLevel.getSelectedItem().toString());
                    ps.setString(3, textLastName.getText());
                     ps.setString(4, comboGender.getSelectedItem().toString());
                   
                     ps.setString(5,textStudentID.getText().trim());
  

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Record Updated");
                  clear();
                  showStudent();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                    clear();
                }
            }
            
        }
        
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to Delete record?","Delete Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
            
            try{
                String sql="delete from Student where StudentID=?";
                ps =con.prepareStatement(sql);
                ps.setString(1, textStudentID.getText().trim());

                // rs=pst.executeQuery();
                ps.execute();
                
                String sql1="delete from verification where fk1_IndexNumber=?";
                ps =con.prepareStatement(sql1);
                ps.setString(1, textStudentID.getText().trim());

                // rs=pst.executeQuery();
                ps.execute();
                
                 String sql2="delete from vericationhistory where StudentID=?";
                ps =con.prepareStatement(sql2);
                ps.setString(1, textStudentID.getText().trim());

                // rs=pst.executeQuery();
                ps.execute();
                
                showStudent();
                JOptionPane.showMessageDialog(null, "Record Deleted");
              clear();

            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
                clear();

            }finally {
                try{
                    rs.close();
                    ps.close();
                    //conn.close();
                }
                catch(Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }

        }

    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        clear();
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed

        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to Save record?","Save Record",JOptionPane.YES_NO_OPTION);
        if(p==0){


            try{
                 if(textStudentID.getText()==null || textFirstName.getText()==null || textLastName.getText()==null|| comboGender.getSelectedItem()==null || CmbLevel.getSelectedItem()==null ){
                JOptionPane.showMessageDialog(null, "One or More Fields is empty");
            }else {
            
            

    ps=con.prepareStatement("INSERT INTO student (STUDENTID,FIRSTNAME,lEVEL,LASTNAME,GENDER) values(?,?,?,?,?)");

                ps.setString(1, textStudentID.getText().trim());
                ps.setString(2, textFirstName.getText());
                ps.setString(3, CmbLevel.getSelectedItem().toString());
                ps.setString(4, textLastName.getText());
                ps.setString(5, comboGender.getSelectedItem().toString());

              
                ps.execute();
               
                JOptionPane.showMessageDialog(null,"Data is saved successfully");
              clear();
              showStudent();
            }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
                clear();

            }
        
            finally {
                try{
                    rs.close();
                    ps.close();
                    //conn.close();
                }
                catch(Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        
        
        }

    }//GEN-LAST:event_buttonSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        homePage a=new homePage();
        this.setVisible(false);
        a.show();
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
 setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

    }//GEN-LAST:event_formWindowClosing

    private void textStudentIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textStudentIDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String sql = "select * from Student where StudentID='"+textStudentID.getText().trim()+"' " ;
            try{
                ps=con.prepareStatement(sql);
                rs=ps.executeQuery();
                if(rs.next()){
                    String ID=rs.getString("StudentID");
                    textStudentID.setText(ID);

                    String fName=rs.getString("FirstName");
                    textFirstName.setText(fName);

                    String level=rs.getString("LEVEL");
                    CmbLevel.setSelectedItem(level);

                    String lName=rs.getString("LastName");
                    textLastName.setText(lName);

                    String sex=rs.getString("GENDER");
                    comboGender.setSelectedItem(sex);

      

                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_textStudentIDKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

 int index;
 
 TableModel model=jTable1.getModel(); 

 int selectedRow = jTable1.getSelectedRow();
 index =Integer.parseInt( model.getValueAt(selectedRow, 0).toString());
 
        String sql = "select * from student where StudentID='"+index+"' " ;
        try{
    ps=con.prepareStatement(sql);
    rs=ps.executeQuery();
    if(rs.next()){
        String id = rs.getString("STUDENTID");
        textStudentID.setText(id);
        
        String name = rs.getString("FIRSTNAME");
        textFirstName.setText(name);
        
        String brand = rs.getString("LEVEL");
        CmbLevel.setSelectedItem(brand);
        
         String qty = rs.getString("LASTNAME");
        textLastName.setText(qty);

        
        String Price = rs.getString("GENDER");
        comboGender.setSelectedItem(Price);

        

    }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",2);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void comboGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboGenderActionPerformed

    private void CmbLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbLevelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbLevel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textStudentID;
    // End of variables declaration//GEN-END:variables


void clear(){
    
    
                textStudentID.setText(" ");
                CmbLevel.setSelectedItem(null);
                textFirstName.setText(" ");
                comboGender.setSelectedItem(null);
                textLastName.setText(" ");

}

}
